[hatena]
consumer_key = "your_hatena_key"
consumer_secret = "your_hatena_secret"

[google]
client_id = "your_google_client_id"
client_secret = "your_google_client_secret"
drive_folder_id = "your_google_drive_folder_id"
